### ISSUE TITLE
Modulo (Stock) > Inventario 

### ISSUE THREAD

**Issue by johanmar23** [jasp402/uniprint#2]
En la tabla de inventario no ingresa al link de la nota de entrega en el detalle de la misma y por ende no imprime las etiquetas deseadas, solo parece tener la opcion de ingresar al ultimo registro, indistintamente de pulsar otro codigo de inventario o nota de entrega

**Comment by kaGabriella** [comment]
Interesante

**Comment by jasp402** [comment]
**Error corregido.**
Ya muestra los detalle de la entrada, sigue el enlace y puede generar las etiquetas

> Quizás falte aun un largo camina para poder visualizar los traslados en la misma tabla y para poder ver los detalles de los traslados de la misma forma en la que se ven las entradas. 
> sin embargo se sugiere que se abra _otro debate con el tema de traslados_ para dar este punto por concluido. 

revisar detalles en [d44c07b](https://github.com/jasp402/uniprint/commit/d44c07ba69b50178dd7a229f05d0f9d7489d5858)

 @johanmar23  @kaGabriella
