### ISSUE TITLE
Descuento de Traslado

### ISSUE THREAD

**Issue by johanmar23** [jasp402/uniprint#5]
Luego de registrar la cantidad de libros trasladados desde el macaro a la julia, no me actualiza el nuevo valor restante.. y sigue apareciendo el anterior

**Comment by jasp402** [comment]
**Error corregido.** 
Se estaba seleccionando mal el campo de la base de datos que se debía restar
revisar detalles en [ 8ea3502  ](https://github.com/jasp402/uniprint/commit/8ea3502827d8f566222309865add09a9b624401e)
